### ISSUE TITLE
[RFE]: More explicit arrow directions

### ISSUE THREAD

**Issue by jayofdoom** [vegeta897/wordle-peaks#23]
Thank you for the game, my wife and I enjoy it greatly. One issue we have though, is while the letter arrows are artistically pretty, they're tough to see well when cast onto a TV screen. It'd be nice to have an option (maybe toggled with High Contrast Mode?) which gives them a sharper arrow shape.

While I'm only mediocre at JS/CSS/HTML, if you're amenable to this feature but don't want to write it, let me know and I may eventually get you a PR.

Thanks!
-Jay

**Comment by vegeta897** [comment]
Hey, thank you for opening an issue and for the kind words!

This is an interesting request since I would have thought people only paid attention to the colors.

I'm resistant to making anything "sharp" per-se, but here's what it looks like when I turn up the rounding to max. Does this read better for you?

![image](https://github.com/user-attachments/assets/63c2e7f3-5bd8-4d74-aa3f-7d4c2565ae19)

I could also take it further like this:

![image](https://github.com/user-attachments/assets/54e4b2f1-fcc6-48a1-8f78-d8deeba8c8d2)

But I don't like how unbalanced they feel.

**Comment by jayofdoom** [comment]
I'll run it by my wife, she's really the one who had the complaint. The bottom one looks AWESOME to me though. An across the board improvement! 

edit: She agrees!

**Comment by vegeta897** [comment]
Thanks for the input. I think I'll add a slider in the options that lets you go from totally square to fully pointed.

Edit: Hey, thank you for sponsoring 🥰

**Comment by vegeta897** [comment]
I think I will also make the default roundness a bit more round, now that I'm looking at these more.

**Comment by vegeta897** [comment]
Here we go! Take a look in the options screen to try it out.

![image](https://github.com/user-attachments/assets/75d9ee71-5ed5-4bb2-b09c-d85f8e5cf799)

I even updated the image share function to use the variable sharpness too.

Thanks again for suggesting this.
