### ISSUE TITLE
"share" content reveals info about solution 😬

### ISSUE THREAD

**Issue by mattdzugan** [vegeta897/wordle-peaks#24]
Hello! I love the game ♥️
([This is me](https://x.com/MattDzugan/status/1822336422512054701?t=BeG2NN3YcE4yw1om2g72bQ&s=19))

Today I wanted to share this game with a friend via the `share` button so they'd see my score etc...

  🔼🔼🔽🔽🔽
  🟩🟩🔽🟩🔼
  🟩🟩🟩🟩🟩

But I believe this actually provides a fairly large hint!!!

My friend would've known that the word has a 3rd letter which is very early alphabetically. And the first two letters must be fairly late alphabetically.

It's a tough decision because the arrows are cute, and allow us to reference the unique feature of this game. But I fear it reveals too much info!!!!

Thoughts?

I can open a PR for a toggle option to replace with plain orange

**Comment by vegeta897** [comment]
Hi! Thanks again for that lovely tweet. And thanks for the star, and opening an issue!

I've always known that the share tiles weren't totally spoiler-free, but didn't consider it much of an issue. I'm certainly open to adding an option though.

I wouldn't want to use orange since that could be confused with representing the orange arrow tiles in the game itself. Maybe purple 🟪

I appreciate the PR offer but I'd prefer to handle this. I already wanted to rework the share section entirely, because I don't like the current cramped layout, or the flow (clicking `share` and _then_ clicking `text` is confusing some people). But I don't want to leave you waiting on all that so I think I'll try to squeeze the option in today.

**Comment by vegeta897** [comment]
Okay, the change is live! Thanks again for the suggestion.

**Comment by mattdzugan** [comment]
wow looks fantastic!!! thanks again

**Comment by mattdzugan** [comment]
just following up to say this has allowed me to now have a few separate text message chains w/ friends where we share (spoiler free) scores! ❤

**Comment by vegeta897** [comment]
Thank you for that follow up, that makes me really happy! 😊
